[colors.normal]
black = "0x000000"
blue = "0x0000ff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[window]
# opacity = 0.6
padding = { x = 8, y = 8 }

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[env]
TERM = "alacritty"

[font]
size = 12

[font.normal]
family = "HackGen Console NF"

[[keyboard.bindings]]
chars = "\u001B[46;5u"
key = "Period"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[32;5u"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[96;5u"
key = "At"
mods = "Control"
